version: "3.8"
services:
    api:
        build:
            context: .
            target: production
            dockerfile: apps/api/Dockerfile
        environment:
            - NODE_ENV=production
            - DB_FILE_PATH=/app/data/db.sqlite
            - MANDATS_PATH=${MANDATS_PATH-./data/mandats}
            - JWT_SECRET=${JWT_SECRET-please_change_me}
            - MS_ACCESS_DB_PATH=${MS_ACCESS_DB_PATH-./data/BEGdatas.mdb}
        volumes:
            - ./data:/app/data
            - $MANDATS_PATH:/mandats
            - $MS_ACCESS_DB_PATH:/export-mdb/beg.mdb:ro
        working_dir: /app/apps/api
        command: bun run start
        restart: always
    app:
        restart: no
        build:
            context: .
            target: production
            dockerfile: apps/app/Dockerfile
        environment:
            - NODE_ENV=production
        volumes:
            - app-dist:/app/apps/app/dist
        working_dir: /app/apps/app
        command:
            - bun
            - run
            - build
    proxy:
        restart: always
        container_name: proxy-beg
        build:
            context: ./provision/nginx
            dockerfile: Dockerfile
            target: production
        depends_on:
            app:
                condition: service_completed_successfully
        volumes:
            - app-dist:/var/www/app:ro
            - ./provision/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
            - ./provision/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        networks:
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.beg.middlewares=default-headers@file
            - traefik.http.routers.beg.entrypoints=https
            - traefik.http.routers.beg.rule=Host(`beg.solioz.dev`)
            - traefik.http.routers.beg.tls=true
            - traefik.http.routers.beg.service=beg
            - traefik.http.services.beg.loadbalancer.server.port=80
            - traefik.docker.network=proxy
networks:
    proxy:
        external: true
volumes:
    app-dist: null
