version: "3.8"

services:
    api:
        build:
            context: .
            target: production
            dockerfile: apps/api/Dockerfile
        environment:
            - NODE_ENV=production
        working_dir: /app/apps/api
        command: bun run start
    app:
        build:
            context: .
            target: production
            dockerfile: apps/app/Dockerfile
        environment:
            - NODE_ENV=production
        volumes:
            - app-static:/app/apps/app/dist
    proxy:
        restart: "on-failure"
        container_name: "proxy"
        build:
            context: ./provision/nginx
            dockerfile: Dockerfile
        volumes:
            - app-static:/var/www/app
            - ./provision/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        develop:
            watch:
                - action: sync+restart
                  path: provision/docker/nginx/nginx.dev.conf
                  target: /etc/nginx/nginx.conf
volumes:
    sqlite-data:
    app-static:
