services:
    mariadb:
        image: mariadb:10.11
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./data/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
            interval: 5s
            timeout: 5s
            retries: 5

    api:
        build:
            context: .
            target: development
            dockerfile: apps/api/Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./apps/api
                  target: /app/apps/api
                  ignore:
                      - node_modules/
                      - drizzle/
                - action: sync+restart
                  path: ./packages
                  target: /app/packages
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: apps/api/package.json
                - action: rebuild
                  path: packages/*/package.json
        environment:
            - NODE_ENV=development
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
        volumes:
            - ./apps/api/drizzle:/app/apps/api/drizzle
            - ./export-mdb:/app/export-mdb
        depends_on:
            mariadb:
                condition: service_healthy
        working_dir: /app/apps/api
        command: bun run dev
        ports:
            - 4983:4983
    app:
        build:
            context: .
            target: development
            dockerfile: apps/app/Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./apps/app
                  target: /app/apps/app
                  ignore:
                      - node_modules/
                - action: sync+restart
                  path: ./packages
                  target: /app/packages
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./apps/app/package.json
                - action: rebuild
                  path: ./packages/*/package.json
        environment:
            - NODE_ENV=development
            - VITE_HMR_HOST=0.0.0.0
            - VITE_HMR_PORT=8080
        working_dir: /app/apps/app
        command: bun run dev

    proxy:
        restart: "on-failure"
        container_name: "proxy"
        build:
            context: ./provision/nginx
            dockerfile: Dockerfile
        ports:
            - 8084:80
        develop:
            watch:
                - action: sync+restart
                  path: ./provision/nginx/nginx.dev.conf
                  target: /etc/nginx/nginx.conf

volumes:
    mariadb-data:
