version: "3.8"

services:
    api:
        build:
            context: .
            target: production
            dockerfile: apps/api/Dockerfile
        environment:
            - NODE_ENV=production
        working_dir: /app/apps/api
        command: bun run start
        restart: always

    proxy:
        restart: always
        container_name: "proxy"
        build:
            context: .
            dockerfile: provision/nginx/Dockerfile.multistage
            target: production
