version: "3.8"

services:
    api:
        build:
            context: .
            target: production
            dockerfile: apps/api/Dockerfile
        environment:
            - NODE_ENV=production
            - DB_FILE_PATH=/app/data/db.sqlite
            - MANDATS_PATH=${MANDATS_PATH-./mandats}
            - JWT_SECRET=${JWT_SECRET-please_change_me}
            - MS_ACCESS_DB_PATH=${MS_ACCESS_DB_PATH-./data/BEGdatas.mdb}
        volumes:
            - ./data:/app/data
            - $MANDATS_PATH:/mandats
            - $MS_ACCESS_DB_PATH:/export-mdb/beg.mdb:ro
        working_dir: /app/apps/api
        command: bun run start
        restart: always

    proxy:
        restart: always
        container_name: "proxy"
        build:
            context: .
            dockerfile: provision/nginx/Dockerfile.multistage
            target: production
