// Country and canton constants for location selection

export const COUNTRIES = {
    CH: "Switzerland",
    FR: "France",
    DE: "Germany",
    IT: "Italy",
    AT: "Austria",
    ES: "Spain",
    GB: "United Kingdom",
    US: "United States",
    CA: "Canada",
    BE: "Belgium",
    NL: "Netherlands",
    LU: "Luxembourg",
    PT: "Portugal",
    PL: "Poland",
    CZ: "Czech Republic",
    SK: "Slovakia",
    HU: "Hungary",
    RO: "Romania",
    BG: "Bulgaria",
    GR: "Greece",
    SE: "Sweden",
    NO: "Norway",
    DK: "Denmark",
    FI: "Finland",
    IE: "Ireland",
    AU: "Australia",
    NZ: "New Zealand",
    JP: "Japan",
    CN: "China",
    IN: "India",
    BR: "Brazil",
    MX: "Mexico",
    AR: "Argentina",
} as const

export const SWISS_CANTONS = {
    AG: "Aargau",
    AI: "Appenzell Innerrhoden",
    AR: "Appenzell Ausserrhoden",
    BE: "Bern",
    BL: "Basel-Landschaft",
    BS: "Basel-Stadt",
    FR: "Fribourg",
    GE: "Geneva",
    GL: "Glarus",
    GR: "Grisons",
    JU: "Jura",
    LU: "Lucerne",
    NE: "Neuchâtel",
    NW: "Nidwalden",
    OW: "Obwalden",
    SG: "St. Gallen",
    SH: "Schaffhausen",
    SO: "Solothurn",
    SZ: "Schwyz",
    TG: "Thurgau",
    TI: "Ticino",
    UR: "Uri",
    VD: "Vaud",
    VS: "Valais",
    ZG: "Zug",
    ZH: "Zurich",
} as const

export type CountryCode = keyof typeof COUNTRIES
export type CantonCode = keyof typeof SWISS_CANTONS